import React, { useState, useEffect } from "react";
import { RefreshCw } from "lucide-react";
import Topbar from "../../components/Topbar";

export default function EmailLogsPage() {
  const [emailData, setEmailData] = useState<{ total_sent: number; total_failed: number; email_logs: any[] }>({
    total_sent: 0,
    total_failed: 0,
    email_logs: []
  });
  const [loading, setLoading] = useState<boolean>(true);

  const fetchEmailLogs = () => {
    setLoading(true);
    fetch("http://localhost:8000/api/admin/emails")
      .then(res => res.json())
      .then(data => {
        if (data && Array.isArray(data.email_logs)) {
          setEmailData(data);
        }
        setLoading(false);
      })
      .catch(err => {
        console.error("Error fetching email logs:", err);
        setLoading(false);
      });
  };

  useEffect(() => {
    fetchEmailLogs();
  }, []);

  return (
    <div className="flex flex-col h-full bg-[#F8FAFC]">
      <Topbar
        crumbs={[{ label: "Admin Operations" }, { label: "Email Logs" }]}
        title="Email Alert Dispatch Logs"
        subtitle="Automated email delivery audit logs generated by Auto Patent Watch scans"
      />

      <main className="flex-1 overflow-y-auto px-8 py-7 space-y-8 max-w-[1440px] mx-auto w-full font-['Inter',sans-serif]">
        <div className="bg-white border border-slate-200/90 rounded-[24px] p-7 shadow-sm space-y-5">
          <div className="flex items-center justify-between border-b border-slate-100 pb-4">
            <div>
              <h3 className="text-[18px] font-extrabold text-slate-900 font-['Space_Grotesk',sans-serif]">
                Email Dispatch Audit Log ({emailData.email_logs.length})
              </h3>
              <p className="text-[12px] font-medium text-slate-500">
                Track email notifications sent to users when new patents, literature, or funding matches are detected.
              </p>
            </div>
            <div className="flex items-center gap-3">
              <span className="px-3 py-1 rounded-full text-[12px] font-bold bg-emerald-100 text-emerald-800">
                {emailData.total_sent} Sent · {emailData.total_failed} Failures
              </span>
              <button
                onClick={fetchEmailLogs}
                className="p-1.5 rounded-[10px] bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold cursor-pointer"
              >
                <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
              </button>
            </div>
          </div>

          <div className="overflow-x-auto">
            {loading ? (
              <div className="py-12 text-center text-slate-400 font-semibold text-[13px]">
                Loading email dispatch audit logs...
              </div>
            ) : emailData.email_logs.length === 0 ? (
              <div className="py-12 text-center text-slate-400 font-semibold text-[13px]">
                No email dispatch logs recorded yet in database.
              </div>
            ) : (
              <table className="w-full text-left text-[13px] border-collapse">
                <thead>
                  <tr className="bg-slate-50 border-b border-slate-200 text-slate-500 font-bold uppercase text-[11px] tracking-wider">
                    <th className="py-3 px-4">Recipient Email</th>
                    <th className="py-3 px-4">Subject Line</th>
                    <th className="py-3 px-4">Delivery Status</th>
                    <th className="py-3 px-4">Retry Count</th>
                    <th className="py-3 px-4">Timestamp</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 font-medium text-slate-700">
                  {emailData.email_logs.map((e) => (
                    <tr key={e.id} className="hover:bg-slate-50/70">
                      <td className="py-3.5 px-4 font-bold text-slate-900">{e.recipient}</td>
                      <td className="py-3.5 px-4">{e.subject}</td>
                      <td className="py-3.5 px-4">
                        <span className={`px-2.5 py-0.5 rounded-full text-[11px] font-extrabold ${e.status === "Sent" ? 'bg-emerald-100 text-emerald-800' : 'bg-red-100 text-red-800'}`}>
                          {e.status}
                        </span>
                      </td>
                      <td className="py-3.5 px-4 text-slate-600 font-bold">{e.retry_count || 0}</td>
                      <td className="py-3.5 px-4 text-slate-500">{e.sent_at ? new Date(e.sent_at).toLocaleString() : 'Recent'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}
